images= \
	img/xlivebg_logo.png \
	img/colcycle.png \
	img/colcycle-thumb.png \
	img/distort.jpg \
	img/distort-thumb.jpg \
	img/guishot.png \
	img/stars.jpg \
	img/stars-thumb.png \
	img/ui_anim_mask.png

.PHONY: all
all: $(images)

%.png %.jpg:
	wget -P img http://nuclear.mutantstargoat.com/sw/xlivebg/manual/$@
