.PHONY: all
all: treestore

.PHONY: clean
clean: clean-treestore

# treestore plugin
.PHONY: treestore
treestore:
	$(MAKE) -C treestore

.PHONY: clean-treestore
clean-treestore:
	$(MAKE) -C treestore clean
