/* this file is generated by ./configure, do not edit */
int img_register_jpeg();
int img_register_lbm();
int img_register_png();
int img_register_ppm();
int img_register_rgbe();
int img_register_tga();

void img_modules_init(void)
{
	img_register_jpeg();
	img_register_lbm();
	img_register_png();
	img_register_ppm();
	img_register_rgbe();
	img_register_tga();
}
